In [ ]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2026.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
!pip install --upgrade jupyter_client

Requirement already satisfied: jupyter_client in /usr/local/lib/python3.12/dist-packages (8.8.0)
Requirement already satisfied: jupyter-core>=5.1 in /usr/local/lib/python3.12/dist-packages (from jupyter_client) (5.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter_client) (2.9.0.post0)
Requirement already satisfied: pyzmq>=25.0 in /usr/local/lib/python3.12/dist-packages (from jupyter_client) (26.2.1)
Requirement already satisfied: tornado>=6.4.1 in /usr/local/lib/python3.12/dist-packages (from jupyter_client) (6.5.1)
Requirement already satisfied: traitlets>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter_client) (5.7.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=5.1->jupyter_client) (4.9.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->jupyter_client) (1.17.0)

In [ ]:
import warnings
warnings.simplefilter("ignore")

In [ ]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules

In [ ]:
df = pd.read_csv('/content/transactions.csv')

In [ ]:
df.head(5)

,order_id,customer_id,restaurant,items,item_names,item_categories,total_price,order_date,order_hour,order_day,n_items,payment_method,delivery_time_min,order_rating
0,ORD00001,CUST0392,El Classico,"M0077,M0250","Veggie Supreme Pizza,Umm Ali","Pizza,Desserts",126.0,2026-04-02,14,Thursday,2,Cash,51,2.6
1,ORD00002,CUST0465,Crave It,"M0296,M0342,M0273,M0343,M0362","Avocado Smoothie,French Onion Soup,Mango Smoot...","Beverages,Soups,Beverages,Soups,Soups",194.0,2026-04-09,20,Thursday,5,Credit Card,26,3.0
2,ORD00003,CUST0428,Urban Bites,"M0324,M0243","Tuna Melt,Tiramisu","Sandwiches,Desserts",87.0,2025-12-12,16,Friday,2,Credit Card,56,4.8
3,ORD00004,CUST0480,Fresh & Fit,"M0120,M0042","Salmon Nigiri (2Pcs),Margherita Pizza","Sushi,Pizza",142.0,2026-04-21,8,Tuesday,2,Wallet,28,4.1
4,ORD00005,CUST0037,Golden Fork,"M0346,M0278","French Onion Soup,Iced Latte","Soups,Beverages",64.0,2025-11-13,12,Thursday,2,Cash,35,4.4

In [ ]:
transactions = df['item_names'].apply(lambda x: x.split(',')).tolist()

clean

In [ ]:
transactions = df['item_names'].apply(
    lambda x: [item.strip() for item in x.split(',')]
).tolist()

trasform 0 ,1

In [ ]:
te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)

df_encoded = pd.DataFrame(te_data, columns=te.columns_)
df_encoded.head()

,Avocado Smoothie,Bbq Bacon Burger,Bbq Chicken Pizza,Blt Sandwich,Caesar Salad,California Roll (8Pcs),Caprese Salad,Cheese Shawarma,Cheesecake Slice,Chicken Noodle Soup,...,Tomato Basil Soup,Truffle Burger,Truffle Mushroom Pizza,Tuna Melt,Umm Ali,Veggie Garden Burger,Veggie Roll (8Pcs),Veggie Supreme Pizza,Waffles & Ice Cream,Watermelon Juice
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df_encoded = df_encoded.astype(bool)

frequent items (suport)

In [ ]:
from mlxtend.frequent_patterns import fpgrowth

frequent_items = fpgrowth(df_encoded, min_support=0.001, use_colnames=True)

print("frequent items =", len(frequent_items))
frequent_items.head(20)

frequent items = 1722

    support                  itemsets
0    0.0720                 (Umm Ali)
1    0.0440    (Veggie Supreme Pizza)
2    0.0535       (French Onion Soup)
3    0.0510        (Avocado Smoothie)
4    0.0455     (Mushroom Cream Soup)
5    0.0280          (Mango Smoothie)
6    0.0370               (Tuna Melt)
7    0.0315                (Tiramisu)
8    0.0515        (Margherita Pizza)
9    0.0395    (Salmon Nigiri (2Pcs))
10   0.0580              (Iced Latte)
11   0.0485  (Spicy Tuna Roll (8Pcs))
12   0.0475       (Quinoa Power Bowl)
13   0.0375            (Blt Sandwich)
14   0.0190   (Chicken Shawarma Wrap)
15   0.0555      (Veggie Roll (8Pcs))
16   0.0635            (Caesar Salad)
17   0.0365        (Bbq Bacon Burger)
18   0.0295    (Strawberry Milkshake)
19   0.0240   (Spicy Jalapeño Burger)

*rules*

List to detect relation

In [ ]:
rules = association_rules(
frequent_items, metric="lift", min_threshold=1)

print("\nAssociation Rules (Top 20):")
print("rules =", len(rules))

rules.head(20)

Association Rules (Top 20):
rules = 2474

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Veggie Supreme Pizza),(Cheesecake Slice),0.0440,0.0575,0.0030,0.068182,1.185771,1.0,0.000470,1.011463,0.163877,0.030457,0.011333,0.060178
1,(Cheesecake Slice),(Veggie Supreme Pizza),0.0575,0.0440,0.0030,0.052174,1.185771,1.0,0.000470,1.008624,0.166225,0.030457,0.008550,0.060178
2,(Veggie Supreme Pizza),(Caesar Salad),0.0440,0.0635,0.0035,0.079545,1.252684,1.0,0.000706,1.017432,0.210998,0.033654,0.017133,0.067332
3,(Caesar Salad),(Veggie Supreme Pizza),0.0635,0.0440,0.0035,0.055118,1.252684,1.0,0.000706,1.011767,0.215392,0.033654,0.011630,0.067332
4,(Veggie Supreme Pizza),(Truffle Burger),0.0440,0.0555,0.0025,0.056818,1.023751,1.0,0.000058,1.001398,0.024268,0.025773,0.001396,0.050932
5,(Truffle Burger),(Veggie Supreme Pizza),0.0555,0.0440,0.0025,0.045045,1.023751,1.0,0.000058,1.001094,0.024563,0.025773,0.001093,0.050932
6,(Veggie Supreme Pizza),(Avocado Smoothie),0.0440,0.0510,0.0030,0.068182,1.336898,1.0,0.000756,1.018439,0.263598,0.032609,0.018105,0.063503
7,(Avocado Smoothie),(Veggie Supreme Pizza),0.0510,0.0440,0.0030,0.058824,1.336898,1.0,0.000756,1.015750,0.265543,0.032609,0.015506,0.063503
8,(Veggie Supreme Pizza),(Cheese Shawarma),0.0440,0.0785,0.0040,0.090909,1.158078,1.0,0.000546,1.013650,0.142782,0.033755,0.013466,0.070932
9,(Cheese Shawarma),(Veggie Supreme Pizza),0.0785,0.0440,0.0040,0.050955,1.158078,1.0,0.000546,1.007329,0.148128,0.033755,0.007276,0.070932
10,(Veggie Supreme Pizza),(French Onion Soup),0.0440,0.0535,0.0025,0.056818,1.062022,1.0,0.000146,1.003518,0.061088,0.026316,0.003506,0.051774
11,(French Onion Soup),(Veggie Supreme Pizza),0.0535,0.0440,0.0025,0.046729,1.062022,1.0,0.000146,1.002863,0.061701,0.026316,0.002855,0.051774
12,"(Veggie Supreme Pizza, Meat Shawarma Wrap)",(French Onion Soup),0.0015,0.0535,0.0010,0.666667,12.461059,1.0,0.000920,2.839500,0.921132,0.018519,0.647825,0.342679
13,"(Veggie Supreme Pizza, French Onion Soup)",(Meat Shawarma Wrap),0.0025,0.0465,0.0010,0.400000,8.602151,1.0,0.000884,1.589167,0.885965,0.020833,0.370739,0.210753
14,"(Meat Shawarma Wrap, French Onion Soup)",(Veggie Supreme Pizza),0.0040,0.0440,0.0010,0.250000,5.681818,1.0,0.000824,1.274667,0.827309,0.021277,0.215481,0.136364
15,(Veggie Supreme Pizza),"(Meat Shawarma Wrap, French Onion Soup)",0.0440,0.0040,0.0010,0.022727,5.681818,1.0,0.000824,1.019163,0.861925,0.021277,0.018802,0.136364
16,(Meat Shawarma Wrap),"(Veggie Supreme Pizza, French Onion Soup)",0.0465,0.0025,0.0010,0.021505,8.602151,1.0,0.000884,1.019423,0.926848,0.020833,0.019053,0.210753
17,(French Onion Soup),"(Veggie Supreme Pizza, Meat Shawarma Wrap)",0.0535,0.0015,0.0010,0.018692,12.461059,1.0,0.000920,1.017519,0.971738,0.018519,0.017217,0.342679
18,"(Veggie Supreme Pizza, Cheese Shawarma)",(Avocado Smoothie),0.0040,0.0510,0.0010,0.250000,4.901961,1.0,0.000796,1.265333,0.799197,0.018519,0.209694,0.134804
19,"(Veggie Supreme Pizza, Avocado Smoothie)",(Cheese Shawarma),0.0030,0.0785,0.0010,0.333333,4.246285,1.0,0.000764,1.382250,0.766800,0.012422,0.276542,0.173036

In [ ]:
rules.iloc[: , 0:7].sort_values(by='lift', ascending=False).head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
1260,"(Iced Latte, Spaghetti Bolognese)","(Truffle Burger, Club Sandwich)",0.0025,0.0020,0.001,0.400000,200.000000
1257,"(Truffle Burger, Club Sandwich)","(Iced Latte, Spaghetti Bolognese)",0.0020,0.0025,0.001,0.500000,200.000000
1258,"(Truffle Burger, Spaghetti Bolognese)","(Iced Latte, Club Sandwich)",0.0045,0.0015,0.001,0.222222,148.148148
1259,"(Iced Latte, Club Sandwich)","(Truffle Burger, Spaghetti Bolognese)",0.0015,0.0045,0.001,0.666667,148.148148
1256,"(Truffle Burger, Iced Latte)","(Club Sandwich, Spaghetti Bolognese)",0.0040,0.0025,0.001,0.250000,100.000000
1261,"(Club Sandwich, Spaghetti Bolognese)","(Truffle Burger, Iced Latte)",0.0025,0.0040,0.001,0.400000,100.000000
1231,"(Truffle Burger, Club Sandwich)","(Cheese Shawarma, Spaghetti Bolognese)",0.0020,0.0055,0.001,0.500000,90.909091
1234,"(Cheese Shawarma, Spaghetti Bolognese)","(Truffle Burger, Club Sandwich)",0.0055,0.0020,0.001,0.181818,90.909091
1232,"(Truffle Burger, Spaghetti Bolognese)","(Cheese Shawarma, Club Sandwich)",0.0045,0.0025,0.001,0.222222,88.888889
1233,"(Cheese Shawarma, Club Sandwich)","(Truffle Burger, Spaghetti Bolognese)",0.0025,0.0045,0.001,0.400000,88.888889
1235,"(Club Sandwich, Spaghetti Bolognese)","(Truffle Burger, Cheese Shawarma)",0.0025,0.0050,0.001,0.400000,80.000000
1230,"(Truffle Burger, Cheese Shawarma)","(Club Sandwich, Spaghetti Bolognese)",0.0050,0.0025,0.001,0.200000,80.000000
2248,"(Waffles & Ice Cream, California Roll (8Pcs))",(Sashimi Platter (12Pcs)),0.0010,0.0245,0.001,1.000000,40.816327
2249,(Sashimi Platter (12Pcs)),"(Waffles & Ice Cream, California Roll (8Pcs))",0.0245,0.0010,0.001,0.040816,40.816327
650,"(Pasta Carbonara, Tiramisu)",(Egg & Avocado Toast),0.0010,0.0255,0.001,1.000000,39.215686
651,(Egg & Avocado Toast),"(Pasta Carbonara, Tiramisu)",0.0255,0.0010,0.001,0.039216,39.215686
2246,"(Sashimi Platter (12Pcs), Waffles & Ice Cream)",(California Roll (8Pcs)),0.0010,0.0280,0.001,1.000000,35.714286
887,"(Penne Arrabiata, Mango Smoothie)",(California Roll (8Pcs)),0.0010,0.0280,0.001,1.000000,35.714286
890,(California Roll (8Pcs)),"(Penne Arrabiata, Mango Smoothie)",0.0280,0.0010,0.001,0.035714,35.714286
2251,(California Roll (8Pcs)),"(Sashimi Platter (12Pcs), Waffles & Ice Cream)",0.0280,0.0010,0.001,0.035714,35.714286

In [ ]:
def get_closed_patterns(frequent_items):
    closed_patterns = []

    for i, row_i in frequent_items.iterrows():
        is_closed = True

        for j, row_j in frequent_items.iterrows():
            if row_i['itemsets'] < row_j['itemsets']:  # proper subset
                if row_i['support'] <= row_j['support']:
                    is_closed = False
                    break

        if is_closed:
            closed_patterns.append(row_i)

    return pd.DataFrame(closed_patterns)

closed_itemsets = get_closed_patterns(frequent_items)
print("Closed Itemsets (Top 20):")
closed_itemsets.head(20)

Closed Itemsets (Top 20):

    support                  itemsets
0    0.0720                 (Umm Ali)
1    0.0440    (Veggie Supreme Pizza)
2    0.0535       (French Onion Soup)
3    0.0510        (Avocado Smoothie)
4    0.0455     (Mushroom Cream Soup)
5    0.0280          (Mango Smoothie)
6    0.0370               (Tuna Melt)
7    0.0315                (Tiramisu)
8    0.0515        (Margherita Pizza)
9    0.0395    (Salmon Nigiri (2Pcs))
10   0.0580              (Iced Latte)
11   0.0485  (Spicy Tuna Roll (8Pcs))
12   0.0475       (Quinoa Power Bowl)
13   0.0375            (Blt Sandwich)
14   0.0190   (Chicken Shawarma Wrap)
15   0.0555      (Veggie Roll (8Pcs))
16   0.0635            (Caesar Salad)
17   0.0365        (Bbq Bacon Burger)
18   0.0295    (Strawberry Milkshake)
19   0.0240   (Spicy Jalapeño Burger)

In [ ]:
def get_max_patterns(frequent_items):
    max_patterns = []

    for i, row_i in frequent_items.iterrows():
        is_max = True

        for j, row_j in frequent_items.iterrows():
            if row_i['itemsets'] < row_j['itemsets']:  # proper subset
                is_max = False
                break

        if is_max:
            max_patterns.append(row_i)

    return pd.DataFrame(max_patterns)
max_itemsets = get_max_patterns(frequent_items)
print("Maximal Itemsets (Top 20):")
max_itemsets.head(20)

Maximal Itemsets (Top 20):

     support                                           itemsets
73    0.0020                    (Veggie Supreme Pizza, Umm Ali)
75    0.0015          (Veggie Supreme Pizza, Bbq Chicken Pizza)
76    0.0015         (Veggie Supreme Pizza, Veggie Roll (8Pcs))
79    0.0010            (Veggie Supreme Pizza, Pasta Carbonara)
81    0.0025             (Veggie Supreme Pizza, Truffle Burger)
82    0.0020      (Veggie Supreme Pizza, Crispy Chicken Burger)
84    0.0015           (Veggie Supreme Pizza, Margherita Pizza)
86    0.0015        (Veggie Supreme Pizza, Mushroom Cream Soup)
89    0.0015          (Veggie Supreme Pizza, Meat Lovers Pizza)
91    0.0010                     (Veggie Supreme Pizza, Kunafa)
92    0.0015             (Veggie Supreme Pizza, Grilled Cheese)
93    0.0020           (Veggie Supreme Pizza, Mixed Grill Wrap)
94    0.0010                 (Veggie Supreme Pizza, Iced Latte)
95    0.0010        (Veggie Supreme Pizza, Rainbow Roll (8Pcs))
96    0.0010                (Veggie Supreme Pizza, Lentil Soup)
97    0.0015        (Veggie Supreme Pizza, Waffles & Ice Cream)
98    0.0010          (Veggie Supreme Pizza, Quinoa Power Bowl)
99    0.0010  (Veggie Supreme Pizza, Meat Shawarma Wrap, Fre...
100   0.0010  (Veggie Supreme Pizza, Cheese Shawarma, Avocad...
101   0.0010  (Veggie Supreme Pizza, Cheesecake Slice, Peppe...

In [ ]:
from mlxtend.frequent_patterns import fpgrowth, association_rules, fpmax
frequent_itemsets_fpmax = fpmax(df_encoded, min_support=0.01, use_colnames=True)
print("Closed Itemsets (Top 20):")
frequent_itemsets_fpmax.head(20)

Closed Itemsets (Top 20):

    support                   itemsets
0    0.0125      (Chicken Noodle Soup)
1    0.0130         (Seafood Linguine)
2    0.0135    (Mushroom Swiss Burger)
3    0.0135              (Greek Salad)
4    0.0150      (Double Smash Burger)
5    0.0185      (Chocolate Lava Cake)
6    0.0190    (Chicken Shawarma Wrap)
7    0.0190     (Veggie Garden Burger)
8    0.0220        (Pastrami Sandwich)
9    0.0240    (Spicy Jalapeño Burger)
10   0.0245  (Sashimi Platter (12Pcs))
11   0.0250        (Mango Panna Cotta)
12   0.0255      (Egg & Avocado Toast)
13   0.0260         (Watermelon Juice)
14   0.0265                  (Lasagna)
15   0.0265   (Truffle Mushroom Pizza)
16   0.0280   (California Roll (8Pcs))
17   0.0280           (Mango Smoothie)
18   0.0295     (Strawberry Milkshake)
19   0.0310          (Seafood Chowder)